# Generated by Django 4.2.6 on 2023-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_staff_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='staffImages'),
        ),
    ]
